### ISSUE TITLE
Error en ejecución con la función shape.

### ISSUE THREAD

**Issue by Marcelo2m97** [DJNGOSolutions/simple-ocr-opencv#1]
Estuve intentando hacer uso de las nuevas funcionalidades que se están desarrollando para la lectura de DUIs y obtuve el siguiente error al momento de ejecutar el archivo _scan.py_:

**AttributeError: 'NoneType' object has no attribute 'shape'**

Este error se produce en la línea de código 16, la cual tiene la siguiente instrucción:

**ratio = image.shape[0] / 500.0**

¿Alguna idea de a qué se puede deber este error?

**Comment by RonaldVega14** [comment]
Realizá una prueba como esta:

print(image)

Pon esto justo después de la variable en la que se almacena tu imagen (En el ejemplo "image" representa el nombre de tu variable). Si en consola te imprime "None" es que no se está guardando bien la imagen y podría ser un error de entorno, si estás trabajando con PyCharm probablemente el entorno virtual en el que estás no lo hayas configurado. Por otro lado, si te imprime matrices en consola, probablemente sea algún problema con la versión de las librerías que hayas descargado para el proyecto o algún issue que tenga que ver con tu computadora en específico.

**Comment by Marcelo2m97** [comment]
Ya realicé la prueba, efectivamente la variable _image_ no estaba recibiendo nada y al imprimirla en consola salía: _None_.
Dado que yo ocupo PyCharm, tomé en cuenta que podía ser mi entorno y efectivamente, creé uno nuevo y dejé de tener este error.

¡Te agradezco tu ayuda!
